# my global config
global:
  scrape_interval: 30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert_rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
#local scrapping

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 