groups:
- name: Node
  rules:

  ######## SEVERITY == CRITICAL ##########
  # HIGH MEMORY USAGE
  - alert: HostHighMemoryLoad
    expr: 100 - (avg_over_time(node_memory_MemAvailable_bytes{job="node-exporter"}[5m]) / avg_over_time(node_memory_MemTotal_bytes{job="node-exporter"}[5m])) * 100 > 85
    for: 1m
    labels:
      severity: critical
    annotations:
      title: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory usage is too high (> 85% used)\n  VALUE = {{ $value }}%"

  # HIGH CPU LOAD
  - alert: HostHighCpuLoad
    expr: 100 - (avg by(job) (rate(node_cpu_seconds_total{mode="idle", job="node-exporter"}[5m])) * 100) > 90
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Host high CPU load (instance {{ $labels.instance }})
      description: "CPU load is > 90%\n  VALUE = {{ $value }}%"


  ######### SEVERITY == WARNING ##############
  # HIGH MEMORY USAGE
  - alert: HostHighMemoryLoad
    expr: 100 - (avg_over_time(node_memory_MemAvailable_bytes{job="node-exporter"}[5m]) / avg_over_time(node_memory_MemTotal_bytes{job="node-exporter"}[5m])) * 100 > 70
    for: 1m
    labels:
      severity: warning
    annotations:
      title: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory usage is too high (> 70% used)\n  VALUE = {{ $value }}%"

  # HIGH CPU LOAD
  - alert: HostHighCpuLoad
    expr: 100 - (avg by(job) (rate(node_cpu_seconds_total{mode="idle", job="node-exporter"}[5m])) * 100) > 75
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Host high CPU load (instance {{ $labels.instance }})
      description: "CPU load is > 75%\n  VALUE = {{ $value }}%"


  ####### SEVERITY == INFO#######
  # HIGH MEMORY USAGE
  - alert: HostHighMemoryLoad
    expr: 100 - (avg_over_time(node_memory_MemAvailable_bytes{job="node-exporter"}[5m]) / avg_over_time(node_memory_MemTotal_bytes{job="node-exporter"}[5m])) * 100 > 50
    for: 1m
    labels:
      severity: info 
    annotations:
      title: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory usage is too high (> 50% used)\n  VALUE = {{ $value }}%"

  # HIGH CPU LOAD
  - alert: HostHighCpuLoad
    expr: 100 - (avg by(job) (rate(node_cpu_seconds_total{mode="idle", job="node-exporter"}[5m])) * 100) > 50
    for: 1m
    labels:
      severity: info
    annotations:
      summary: Host high CPU load (instance {{ $labels.instance }})
      description: "CPU load is > 50%\n  VALUE = {{ $value }}%"

  # NETWORK ERRORS
  - alert: HostNetworkReceiveErrors
    expr: rate(node_network_receive_errs_total{job="node-exporter"}[2m]) / rate(node_network_receive_packets_total{job="node-exporter"}[2m]) > 0
    for: 1m
    labels:
      severity: info
    annotations:
      summary: Host Network Receive Errors (instance {{ $labels.instance }})
      description: "Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} receive errors in the last two minutes.\n  VALUE = {{ $value }}"

  - alert: HostNetworkTransmitErrors
    expr: rate(node_network_transmit_errs_total{job="node-exporter"}[2m]) / rate(node_network_transmit_packets_total{job="node-exporter"}[2m]) > 0
    for: 1m
    labels:
      severity: info
    annotations:
      summary: Host Network Transmit Errors (instance {{ $labels.instance }})
      description: "Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} transmit errors in the last two minutes.\n  VALUE = {{ $value }}"