{
 "title": "Docker and OS metrics 2",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (job) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id !~\"/\", job=\"cadvisor\"}[5m]))"
    }
   ]
  },
  {
   "title": "Actual cpu freq",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (cpu) (node_cpu_scaling_frequency_hertz{cpu=\"0\", job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node-exporter\"}"
    }
   ]
  },
  {
   "title": "Network Traffic IN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\", job=\"node-exporter\"}[5m]) * 8",
     "legendFormat": "RECEIVED"
    }
   ]
  },
  {
   "title": "Network Traffic OUT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\", job=\"node-exporter\"}[5m]) * 8",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Disk IN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\"}[1m])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Disk OUT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\"}[1m])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    }
   ]
  },
  {
   "title": "Disks usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\", mountpoint=~\"/|/srv.*\"} - node_filesystem_free_bytes{job=\"node-exporter\", mountpoint=~\"/|/srv.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=\"\", job=\"cadvisor\"}[2m])) by (name) * 8",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\", job=\"cadvisor\"}[2m])) by (name) * 8",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\", job=\"cadvisor\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\", job=\"cadvisor\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\", job=\"cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\", job=\"cadvisor\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\", job=\"cadvisor\"}-container_memory_usage_bytes{name!=\"\", job=\"cadvisor\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\", job=\"cadvisor\"}) by (name)"
    }
   ]
  }
 ]
}