version: '3.8'

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    networks:
      - uptimekuma
    ports:
      - "3001:3001"
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
networks:
  uptimekuma:
    name: uptimekuma